### ISSUE TITLE
Possible to get screenshot from Mac of PySimpleGUI tabs?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [mrstephenneal/pdfconduit#4]
Noted a comment that tabs look ugly on a Mac.

Would it be possible to get a screenshot?

Do you think this is a tkinter problem specifically or is there something I can do to improve it?

**Comment by mrstephenneal** [comment]
Honestly not sure if it is something that you can improve, could just be an problem with tkinter.

Below are screenshots of the Windows 10 GUI, MacOS GUI (columns enabled), MacOS GUI (columns disabled)
![screen shot 2018-08-28 at 11 12 44 am](https://user-images.githubusercontent.com/23200215/44732907-58799b80-aab4-11e8-9ad9-7021170c9a3b.png)
![screen shot 2018-08-28 at 11 16 39 am](https://user-images.githubusercontent.com/23200215/44732908-58799b80-aab4-11e8-8f25-bbef868d2ade.png)
![screen shot 2018-08-28 at 11 16 50 am](https://user-images.githubusercontent.com/23200215/44732909-58799b80-aab4-11e8-9bfa-168ea06863d7.png)

**Comment by MikeTheWatchGuy** [comment]
OK, it looks like the background color for your "normal form" is white.
The background color on your tabbed form seems to be '#ececec'

Can you please add a call to SetOptions to change the default background color?
    sg.SetOptions(background_color='white')

**Comment by MikeTheWatchGuy** [comment]
I just posted a new release to the Master Branch.  It should help with the Mac buttons because they will all default to the system color (unless specified explicitly somewhere)

I'm relieved the background is fixed!!  Whew.  That would have made tabs completely unusable.

I'll look further into the ugly tab problem.

Please keep the bug reports coming.  I'll keep fixing them.

**Comment by MikeTheWatchGuy** [comment]
Tabs 

I've just studied up a bit.  There are a LOT of customizations I can do on tabs!  

Do you have any examples you can give me that I could use as a target of sorts?

I need to understand the tkinter Style mechanisms better.   I have a bug opened already that deals with Styles.  

I would like to expose these things as much as possible to the caller so you guys can tweak all you want.  The default have to look great either way.
